version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: triviador_postgres_db
    restart: always
    environment:
      POSTGRES_USER: triviador_user
      POSTGRES_PASSWORD: triviador_pass
      POSTGRES_DB: triviador
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

